"""Add system_settings table

Revision ID: b07005c02e23
Revises: eae7371e8a32
Create Date: 2026-05-02 16:53:50.757886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07005c02e23'
down_revision: Union[str, Sequence[str], None] = 'eae7371e8a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('ollama_base_url', sa.String(), nullable=True),
    sa.Column('ollama_model', sa.String(), nullable=True),
    sa.Column('openai_api_key', sa.String(), nullable=True),
    sa.Column('openai_model', sa.String(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
