"""Add scheduler columns to users

Revision ID: eae7371e8a32
Revises: dbbddb94c27e
Create Date: 2026-05-02 15:44:12.360446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae7371e8a32'
down_revision: Union[str, Sequence[str], None] = 'dbbddb94c27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('morning_tip_enabled', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('morning_tip_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'morning_tip_time')
    op.drop_column('users', 'morning_tip_enabled')
    # ### end Alembic commands ###
